package com.ravisugara.sociallogin.uital

object Key {
    const val PREF_KEY = "MyKey"
    const val IMAGE_PATH_VACCINATION_DOC = "image_path"
    const val EMAIL_MEONLY = "userEmailMeonly"
    const val MOBILE_NUMBER = "user_phone"
    const val PROFILE_PIC_PATH = "profile_pic_path"
    const val LANGUAGE_KEY_ENGLISH = "en"
    const val LANGUAGE_KEY_HEBREW = "iw"
    const val LANGUAGE_ENGLISH = "English"
    const val LANGUAGE_HEBREW = "Hebrew"
    const val FIRST_NAME = "first_name"
    const val LAST_NAME = "last_name"
    const val EMAIL = "email"
    const val PUBLIC_PROFILE = "public_profile"
    const val FIELDS = "fields"
    const val ID = "id"
    const val QR_IMAGE ="ORCodeImage.png"
    const val DATE_FORMATE_YMD ="yyyy-MM-dd"
    const val DATE_FORMATE_MDY ="MM/dd/yyyy"
    const val FILE_PROVIDER = "com.sdei.checkmate.FileProvider"
    const val FILE_NAME ="file"
    const val FILE_NAME_MULTI ="image[]"

    const val DOSE11 ="1/1"
    const val DASH ="-"
    //  const val userPhone2 ="user_phoneee"
    const val COUNTRY = "country"
    const val ADDRESS = "address"
    const val CITY = "city"
    const val ZIP_CODE = "zipCode"
    const val STATE = "state"
    const val STATE_ID = "stateID"
    const val BIRTH_DATE = "birthDate123"
    const val MIME_TYPE = "text/html"
    const val UTF_TYPE = "utfType"
    const val SEX = "sex"
    const val PDF_FILE_NAME_GREEN_PASSPORT ="green_passport_report.pdf"
    const val PDF_FILE_VACCINATION_REPORT ="vaccine_report_33.pdf"
    const val MEONLY_LOGIN_VARIFICATION_STATUS = "v_status"
    const val TOKEN = "token"
    const val TOKEN_MEONLY = "token_meonly"
    const val ACCESS_TOKEN_1UP = "access_token12"
    const val URL_1UPHELATH_CONNECT ="https://api.1up.health/connect/system/clinical/"
    const val ACCESS_TOKEN_KEY_1UP ="&access_token="
    const val USER_ID = "user_id"//int
    const val GRANT_TYPE = "client_credentials"
    const val CLIENT_ID_MEONLY_LOGIN = "v5LoMfRWpJFhXNe97MQbv6ZS0l2icyxY1E7QZxS1"
    const val CLIENT_SECRET_MEONLY_LOGIN =
        "d6PRTNx5umhLUaIE3P6ZA5JzSxtyf16x18aedWUWL316PFth3Lot7NgPFYFVZI3TXWcIeRMRgFjhq8rnxTLKQRZqvuZiJaHJCH7gIqJGvs9bggvhHUMfmnqNN6Ro6GDL"
    const val CALLBACK_URL_MEONLY_LOGIN = "https://mscore.stagingsdei.com:9149/api/MeOnly/AddMeOnlyResponse"
    const val CLIENT_ID_LIVENESS = "VkI4VniZMAnKE0PsZyB8ICnssEPHp9zTOHzLcInL"
    const val CLIENT_SECRET_LIVENESS =
        "1aRjVFaerujIDRBh8y4AWfMaGTaoKrFGGXPFxuapf0xXOxokaasbG37ztTakO3h3d6Q3sHsBk4E46nvAY7njCoUiJfA2gILzYC59ojlmtbHubWInutU6Kk4nql8zMppM"
    const val REDIRECT_URL = "checkmateapp://login/?token="
    const val TOKEN_TYPE = "Bearer"
    const val CLIENT_ID_1UP = "?client_id=4869d854c0856e5617bbbc47d5d62727"
    const val LOGIN_STATUS = "login_status"
    const val EXISTS_USER_STATUS = "user_status"
    const val ADD_USER_STATUS = "statusAddUser"

    const val FACEBOOK_LOGIN_STATUS = "fb_log_status"
    const val GOOGLE_LOGIN_STATUS = "google_log_status"
    const val DEVICE_TOKEN = "de_token"
    const val LIVENESS_TOKEN = "de_token_meonly"
    const val COVID_RESULT_ID = "result_id"
    const val LOGIN_TYPE = "login_type"
    const val LOGIN_TYPE_MEONLY = "meonly"
    const val LOGIN_TYPE_SOCIAL_MEDIA = "social_media"
    const val LANGUAGE_NAME = "lun_name"
    const val LANGUAGE_ID = "lun_id"
    const val LANGUAGE_ID_EN = 2
    const val LANGUAGE_ID_HB = 1
    const val COUNTRY_ID = "country_id"
    const val COUNTRY_CODE_IR = "+972"
    const val COUNTRY_CODE_US = "+1"
    const val COUNTRY_ID_US = 2
    const val COUNTRY_ID_IR = 1
    const val TZ_NO = "tzNumberll"
    const val PASSPORT_NO = "passportNumberff"
    const val STATUS_VACCINATED = "isVaccinatedee"
    const val STATUS_COVID = "wasCovidPatientdd"

    const val REMAINDER_DATE = "date_remainder"
    const val REMAINDER_DATE_2 = "date_remainder2"
    const val VACCINATION_DATE = "vaccination_date"
    const val VACCINATION_DATE_2 = "vaccination_date2"
    const val VACCINATION_DATE_3 = "vaccination_date3"
    const val VACCINATION_COUNTRY = "vaccination_country"
    const val VACCINATION_COUNTRY_ID = "vaccination_country_id"
    const val VACCINATION_STATE = "vaccination_state"
    const val VACCINATION_STATE_ID = "vaccination_stateId"
    const val SHOT_COMPANY = "shot_company"
    const val SHOT_COMPANY_ID = "shot_companyId"
    const val VACCINATION_DOC_PATH = "vicc_doc"
    const val VACCINE_BATCH_NAME = "vicc_info"
    const val VACCINE_BATCH_NAME_2 = "vicc_info2"
    const val VACCINE_BATCH_NAME_3 = "vicc_info3"

    const val STATUS_UPDATE_SHOT = "st_up_s"
    const val STATUS_SHOW_STATE = "statusShowState_jj"
    const val STATUS_HIDE_REMINDER_DATE = "st_remi_d"
   // const val vaccinationId = "viccinton_id"
    const val STATUS_SAVE_DATA = "data_save"
    const val STATUS_SHOW_DOSE_3 = "statusShowDose3"
    const val STATUS_SHOW_DOSE_2 = "statusShowDose2"
    const val STATUS_SHOW_CHECKBOX_2 = "statusShowCheckBox2"
    const val STATUS_SHOW_CHECKBOX_3 = "statusShowCheckBox3"
    const val STATUS_REMAINDER_DATE_2 = "statusReminderDate2e"

    const val STATUS_SHOW_TUTORIAL1 = "statusShowTutorial1"
    const val STATUS_SHOW_TUTORIAL2 = "statusShowTutorial2"
   // const val statusShowTutorial3 = "statusShowTutorial3"
    const val STATUS_LIVENESS_VARIFICATION = "statusShowTutorial4"
    const val VACCINATION_REQUEST_ID = "id_request_liveness"
    const val LANGUAGE_TYPE = "language_type"
    const val STATUS_1UP = "status1uphealth"
    const val ID_1UP = "idhjhj1uphealth"
    const val LOGIN_COUNT_MEONLY = "loginCount"
    const val PDF_URL_PATH = "pdfUrlPath"
    const val VERIFY_COUNT_MEONLY = "verifyCountMeonly"
    const val GIF_TYPE = "GifType"
    const val GIF_CORONA = "corona"
    const val GIF_VACCINATION = "vaccination"
    const val GIF_SCAN = "scan"

    //result
    const val GET_RESULT ="result"
    const val GET_FIRST_NAME ="FirstName"
    const val GET_LAST_NAME ="LastName"
    const val GET_VACCINATION ="Vaccination"
    const val GET_VACCINATION_ID ="VaccinationId"
    const val GET_VACCINATION_SHOT ="ShotsVaccineInfolst"
    const val GET_SHOT_1 ="1"

    const val GET_COMPANY_NAME ="CompanyName"
    const val REQURED_SHOTS = "RequredShots"
    const val COMPLETED_SHOTS = "completedShotsCount"
    const val GET_VACCINATION_DATE ="VaccinationDate"
    const val GET_STATE_NAME ="StateName"
    const val GET_COUNTRY_NAME ="CountryName"
    const val GET_CORONA_RESULT ="Result"
    const val GET_PATIENT_ID ="PatientCovidResultId"
   // const val get =""


    const val KEY_EMAIL = "KEY_TITLE"
    const val KEY_FIRSTNAME = "KEY_FIRSTNAME"
    const val KEY_LASTNAME = "KEY_LASTNAME"
    const val KEY_LOGINTYPE = "KEY_LOGINTYPE"
    const val EMAIL_GOOGLE ="EMAIL"
    const val DEFAULT_COUNTRY = "US"
    const val IMAGE_TYPE ="image/png"
    const val PRINT_JOB_NAME ="Document"
    const val FILE_TYPE_SHARE ="*/*"

    // const val status1UpHealth = "status1UpHealth"


    //7061737323313233


}